#!/system/xbin/sh

# Sweep2Wake
# possible values:
# 0 = off
# 1 = on
# 2 = on without button backlights
SWEEP2WAKE=0

# Badass
# possible values
# 1 = performance
# 2 = balanced
# 3 = battery saving
BADASS=2

# ZRAM
ZRAM=0

# TUN
TUN=0

### DO NOT CHANGE ANYTHING BELLOW THIS LINE! ###

$L "setting sweep2wake to ${SWEEP2WAKE}"
echo ${SWEEP2WAKE} > /sys/android_touch/sweep2wake

CUR_GOV="`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`"
echo badass > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
case ${BADASS} in
	1)
		$L "badass: setting performance oriented configuration"
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1512000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 120 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 8 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 4 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 150 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 50 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 300 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
		echo 450 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
	;;
	2)
		$L "badass: setting balanced configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 130 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 100 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 14 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 6 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 260 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 180 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 700 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
		echo 500 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
	;;
	3)
		$L "badass: setting battery saving configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 140 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 110 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 20 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 300 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 250 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 750 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
		echo 600 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
	;;
esac
echo ${CUR_GOV} > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

if [ "${ZRAM}" = "1" ]; then
	if [ -e /sys/block/zram0/disksize ] ; then
		$L "Setting ZRAM disksize."
		echo $((100*1024*1024)) > /sys/block/zram0/disksize

		mkswap /dev/block/zram0
		swapon /dev/block/zram0
		$L "ZRAM activated."
	fi
fi

if [ "${TUN}" = "1" ]; then
	if [ -e /system/lib/modules/tun.ko ] ; then
		insmod /system/lib/modules/tun.ko
		$L "Inserted tun kernel module."
	fi
fi
